/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * stock.java
 *
 * Created on Jul 26, 2019, 2:27:51 AM
 */

package inventory_project;

import java.sql.*;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
 
 
 
public class stock extends javax.swing.JFrame
{
 JLabel l10,l2,l3,l4,l5,l6;
    JTextField t3,t4,t5;
    JComboBox c;
    JButton b1,b2,b3,b4,b5;
    ImageIcon i1;

    /** Creates new form stock */
    public stock()
    {


        setLayout(null);
        setTitle("Stock Entry");
        l10=new JLabel("Enter The Stock Details");
        l10.setBounds(400,100,600,60);
        Font f=new Font("aprajita",Font.ITALIC,50);
        l10.setForeground(Color.red);
        l10.setFont(f);

        l2=new JLabel("Item Code");
        l2.setBounds(450,200,150,40);
        l2.setForeground(Color.black);
        Font f1=new Font("chiller",Font.BOLD|Font.ITALIC,30);
        l2.setFont(f1);
        c=new JComboBox();
         c.setBounds(680,200,150,30);

        l3=new JLabel("Item Name");
         Font f2=new Font("chiller",Font.BOLD|Font.ITALIC,30);
         l3.setFont(f2);
         l3.setBounds(450,280,150,40);
         t3=new JTextField();
         t3.setBounds(680,280,150,30);

         l4=new JLabel("Rate per Kilo");
          Font f3=new Font("chiller",Font.BOLD|Font.ITALIC,30);
        l4.setFont(f3);
        l4.setBounds(450,350,200,40);
        t4=new JTextField();
        t4.setBounds(680,350,150,30);

        l5=new JLabel("Quantity on Hand");
         Font f4=new Font("chiller",Font.BOLD|Font.ITALIC,30);
         l5.setFont(f4);
         l5.setBounds(450,420,200,40);
         t5=new JTextField();
         t5.setBounds(680,430,150,30);
         

         b1=new JButton("Insert");
         Font f5=new Font("Courier New",Font.BOLD,18);
         b1.setFont(f5);
         b1.setForeground(Color.red);
         b1.setBackground(Color.yellow);
         b1.setBounds(380,520,100,50);
         

         b2=new JButton("Update Items");
         Font f6=new Font("courier new",Font.BOLD,18);
         b2.setFont(f6);
         b2.setBackground(Color.yellow);
         b2.setForeground(Color.red);
         b2.setBounds(500,520,200,50);
         

         b3=new JButton("Clear All");
         Font f7=new Font("courier new",Font.BOLD,18);
         b3.setForeground(Color.red);
         b3.setBackground(Color.yellow);
         b3.setFont(f7);
         b3.setBounds(720,520,150,50);
        

         b4=new JButton("Exit");
         Font f8=new Font("courier new",Font.BOLD,18);
         b4.setForeground(Color.yellow);
         b4.setBackground(Color.red);
         b4.setFont(f8);
         b4.setBounds(890,520,100,50);
        

         b5=new JButton("Back To Login");
         Font f9=new Font("courier new",Font.BOLD,18);
         b5.setFont(f9);
         b5.setForeground(Color.red);
         b5.setBackground(Color.yellow);
         b5.setBounds(535,600,300,50);
        

        



        add(l10);
        add(l2);
        add(c);
        add(l3);
        add(t3);
        add(l4);
        add(t4);
        add(l5);
        add(t5);
        add(b1);
        add(b2);
        add(b3);
        add(b4);
        add(b5);
        




    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        l1.setIcon(new javax.swing.ImageIcon("D:\\javawork\\PROJECT\\Inventory_Project\\src\\inventory_project\\image4.jpg")); // NOI18N
        l1.setText("jLabel1");
        l1.setMaximumSize(new java.awt.Dimension(1368, 768));
        l1.setMinimumSize(new java.awt.Dimension(1958, 1080));
        l1.setPreferredSize(new java.awt.Dimension(1366, 768));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(602, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(323, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new stock().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel l1;
    // End of variables declaration//GEN-END:variables

}
