/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * welcome.java
 *
 * Created on Jul 27, 2019, 4:43:25 PM
 */

package inventory_project;

import javax.swing.JOptionPane;


/**
 *
 * @author Acer
 */
public class welcome extends javax.swing.JFrame
{
      

    /** Creates new form welcome */
    public welcome()
    {
         
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Baskerville Old Face", 1, 100)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 0));
        jLabel2.setText("STOCK");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(500, 190, 440, 90);

        jLabel3.setFont(new java.awt.Font("Baskerville Old Face", 1, 80)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("MANAGEMENT");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(390, 300, 660, 80);

        jLabel4.setFont(new java.awt.Font("Baskerville Old Face", 1, 100)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 255, 0));
        jLabel4.setText("SYSTEM");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(470, 400, 460, 100);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(480, 280, 420, 10);

        jSeparator1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(520, 380, 340, 10);

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\javawork\\PROJECT\\stock_control_system\\Inventory_Project\\src\\inventory_project\\background.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setPreferredSize(new java.awt.Dimension(500, 500));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -20, 1366, 768);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[])
    {
       
        try
        {
            Thread.sleep(5000);
            login o=new login();
		o.setSize(1366,770);
        o.setVisible(true);
        
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables

}
